import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type ReminderDocument = Reminder & Document;

@Schema({ timestamps: true })
export class Reminder {
  @Prop({ required: true, index: true })
  petId: string;

  @Prop({ required: true })
  petName: string;

  @Prop({ default: '#f97316' })
  petColor: string;

  @Prop({ required: true, index: true })
  userId: string;

  @Prop({ type: [String], default: [] })
  coParentIds: string[];

  @Prop({ required: true })
  title: string;

  @Prop({
    enum: [
      'food',
      'vaccine',
      'medication',
      'vet_visit',
      'grooming',
      'walking',
      'sitting',
      'custom',
    ],
    default: 'custom',
  })
  type: string;

  @Prop({ required: true, index: true })
  dueDate: string; // YYYY-MM-DD

  @Prop()
  dueTime?: string;

  @Prop({
    enum: ['once', 'daily', 'weekly', 'monthly', 'yearly'],
    default: 'once',
  })
  recurrence: string;

  @Prop()
  notes?: string;

  @Prop({ default: false })
  isCompleted: boolean;

  @Prop({ default: false })
  isAutoGenerated: boolean;

  @Prop()
  completedAt?: Date;
}

export const ReminderSchema = SchemaFactory.createForClass(Reminder);
