import React from 'react';
import { X, Printer } from 'lucide-react';
import './FinancialReportsTab.css';

interface ReportPrintModalProps {
  type: 'X_REPORT' | 'Z_REPORT';
  storeName: string;
  orders: any[];
  onClose: () => void;
}

export const ReportPrintModal: React.FC<ReportPrintModalProps> = ({
  type,
  storeName,
  orders,
  onClose,
}) => {
  const isX = type === 'X_REPORT';
  const reportTitle = isX ? 'DAILY SHIFT READING (X-REPORT)' : 'END-OF-PERIOD ACCOUNTING (Z-REPORT)';
  const now = new Date().toLocaleString();

  const pickupOrders = orders.filter((o) => o.subOrder?.deliveryMode === 'pickup');
  const deliveryOrders = orders.filter((o) => o.subOrder?.deliveryMode !== 'pickup');

  const totalGross = orders.reduce((sum, o) => sum + (o.subOrder?.subtotalAmount || 0), 0);
  const totalDeliveryFees = deliveryOrders.reduce((sum, o) => sum + (o.subOrder?.deliveryFee || 0), 0);
  const totalItems = orders.reduce((sum, o) => sum + (o.subOrder?.items?.length || 0), 0);
  const completedCount = orders.filter((o) => o.subOrder?.status === 'delivered').length;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="store-modal-overlay" onClick={onClose}>
      <div className="report-print-card animate-scale-up" onClick={(e) => e.stopPropagation()}>
        <div className="report-print-header">
          <div>
            <h3>{reportTitle}</h3>
            <small>{storeName} · Generated {now}</small>
          </div>
          <button type="button" className="btn-close-modal" onClick={onClose}><X size={18} /></button>
        </div>

        <div className="report-paper-body">
          <div className="receipt-header">
            <h4>🏪 {storeName}</h4>
            <p>PetSOS Merchant Terminal #POS-01</p>
            <div className="receipt-divider" />
          </div>

          <div className="receipt-row">
            <span>Report Type:</span>
            <strong>{isX ? 'X-Reading (Open Shift)' : 'Z-Close (Financial Period)'}</strong>
          </div>
          <div className="receipt-row">
            <span>Period Date:</span>
            <span>{new Date().toISOString().split('T')[0]}</span>
          </div>
          <div className="receipt-row">
            <span>Total Orders:</span>
            <strong>{orders.length} ({completedCount} Fulfilled)</strong>
          </div>
          <div className="receipt-row">
            <span>Fulfillment Split:</span>
            <span>{pickupOrders.length} In-Store Pickup | {deliveryOrders.length} Courier Delivery</span>
          </div>
          <div className="receipt-row">
            <span>Total Units Sold:</span>
            <span>{totalItems} items</span>
          </div>

          <div className="receipt-divider" />

          <div className="receipt-row">
            <span>Gross Store Merchandise Sales:</span>
            <strong>₪{totalGross.toFixed(2)}</strong>
          </div>
          <div className="receipt-row">
            <span>DaaS Courier Delivery Fees ({deliveryOrders.length} orders):</span>
            <span>₪{totalDeliveryFees.toFixed(2)}</span>
          </div>
          <div className="receipt-row">
            <span>Store In-Pickup Fees ({pickupOrders.length} orders):</span>
            <span>₪0.00 (FREE)</span>
          </div>
          <div className="receipt-row receipt-total-row">
            <span>NET STORE MERCHANDISE REVENUE:</span>
            <strong>₪{totalGross.toFixed(2)}</strong>
          </div>
          <div className="receipt-row" style={{ fontSize: '0.75rem', color: '#94a3b8', marginTop: '0.25rem' }}>
            <span>Total Gross Transaction Value:</span>
            <span>₪{(totalGross + totalDeliveryFees).toFixed(2)}</span>
          </div>

          <div className="receipt-divider" />
          <small className="receipt-tax-note">
            Official accounting receipt generated by PetSOS Platform. {isX ? 'Shift remains open.' : 'Period closed & archived.'}
          </small>
        </div>

        <div className="report-print-actions">
          <button type="button" className="btn-cancel" onClick={onClose}>Close</button>
          <button type="button" className="btn-print-report" onClick={handlePrint}>
            <Printer size={15} /> Print / Export PDF
          </button>
        </div>
      </div>
    </div>
  );
};
