import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'he' | 'ar' | 'es' | 'ru' | 'fr' | 'de' | 'it' | 'pt';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeName: string;
  flag: string;
  dir: 'ltr' | 'rtl';
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeName: 'English', flag: '🇺🇸', dir: 'ltr' },
  { code: 'he', label: 'Hebrew', nativeName: 'עברית', flag: '🇮🇱', dir: 'rtl' },
  { code: 'ar', label: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'es', label: 'Spanish', nativeName: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'ru', label: 'Russian', nativeName: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'fr', label: 'French', nativeName: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'de', label: 'German', nativeName: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'it', label: 'Italian', nativeName: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
  { code: 'pt', label: 'Portuguese', nativeName: 'Português', flag: '🇧🇷', dir: 'ltr' },
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    'nav.emergency': 'Emergency',
    'nav.community': 'Community',
    'nav.assistant': 'Assistant',
    'nav.pets': 'Health & Pets',
    'nav.shops': 'Shops',

    'action.save': 'Save Changes',
    'action.cancel': 'Cancel',
    'action.delete': 'Delete',
    'action.edit': 'Edit',
    'action.back': 'Back',
    'action.close': 'Close',
    'action.logout': 'Log Out',
    'action.login': 'Sign In',
    'action.register': 'Register',
    'action.share': 'Share',
    'action.archive': 'Archive Pet',
    'action.restore': 'Restore Pet',
    'action.call': 'Call Clinic',
    'action.directions': 'Directions',
    'action.dispatch': 'Dispatch SOS Dossier',
    'common.select_language': 'Select Language',

    'emergency.title': 'Emergency Vets Near You',
    'emergency.subtitle': 'Real-time open clinic finder, live triage queue & SOS dispatch',
    'emergency.search_placeholder': 'Search city (current: Haifa)...',
    'emergency.filter_all': 'All Clinics',
    'emergency.filter_open': '🟢 Open Now',
    'emergency.filter_verified': '⭐ Verified PIMS Direct',
    'emergency.filter_247': '⭐ 24/7 ER Only',
    'emergency.filter_immediate': '🚨 Immediate Intake',
    'emergency.sos_banner_title': '🚨 PET IN CRITICAL DISTRESS?',
    'emergency.sos_banner_desc': 'Immediate 24/7 Veterinary Emergency Hotline: +972-54-998-1122',
    'emergency.btn_call_emergency': 'CALL EMERGENCY HOTLINE NOW',
    'emergency.vets_nearby_prefix': 'vets nearby',
    'emergency.sheet_drag_hint': 'Drag to adjust',
    'emergency.tag_verified_er': 'VERIFIED 24/7 ER',
    'emergency.tag_community_open': 'COMMUNITY VET · OPEN NOW',
    'emergency.tag_closed': 'CLOSED NOW',
    'emergency.btn_alert_coming': "🚨 Alert Clinic I'm Coming",
    'emergency.btn_call': 'Call',
    'emergency.btn_directions': 'Directions',

    'community.title': 'Community & Safety',
    'community.subtitle': 'Stories, Amber Alerts & Local Pet Moments',
    'community.share_moment': 'Share Moment',
    'community.add_story': 'Add Story',
    'community.my_pet': 'My Pet+',
    'community.expire_24h': '24h Expire',
    'community.filter_all': 'All Moments',
    'community.filter_lost': '🚨 Lost & Found (30d)',
    'community.filter_health': '🩺 Vet & Health Tips',
    'community.filter_playdate': '🐕 Playdates',
    'community.filter_cute': '✨ Cute Snaps',
    'community.call_owner': 'Call Owner Immediately',
    'community.comment_placeholder': 'Add a reply or tip...',
    'community.translate_btn': 'Translate Post',
    'community.show_original': 'Show Original',
    'community.tag_health': '🩺 HEALTH & CARE',
    'community.tag_cute': '✨ CUTE SNAP',
    'community.tag_playdate': '🐕 PLAYDATE',
    'community.tag_lost': '🚨 LOST SOS',
    'community.pet_post': 'Pet Post',

    'profile.title': 'My Pets',
    'profile.managed_by': 'Managed by',
    'profile.active_pets': '🐾 Active Pets',
    'profile.archived_pets': '📦 Archived Passports',
    'profile.add_pet': 'Add New Pet',
    'profile.no_pets': 'No pets in this list yet.',
    'profile.no_archived': 'No archived pet passports.',
    'profile.archived_badge': 'ARCHIVED',
    'profile.passport_heading': 'VERIFIED HEALTH PASSPORT & CLINICAL HISTORY',
    'profile.tab_vet_records': 'Vet Verified Records',
    'profile.tab_home_log': 'Home Log',
    'profile.tab_spending': 'Spending Breakdown',
    'profile.btn_scan_record': 'Scan Past Record / Receipt',
    'profile.btn_export_pdf': 'Export Health Passport',
    'profile.analytics_title': 'Lifetime & Monthly Spending Analytics',
    'profile.total_tracked': 'Total Tracked',
    'profile.avg_monthly': 'Avg. Monthly Cost',
    'profile.receipts_analyzed': 'Receipts Analyzed',

    'chat.title': 'PetSOS AI Assistant',
    'chat.subtitle': 'Guardrailed pet wellness, nutrition & emergency triage support',
    'chat.input_placeholder': 'Ask anything about pet care, symptoms, diet...',
    'chat.send': 'Send',

    'market.title': 'Pet Shops',
    'market.subtitle': 'Premium food, toys & pharmacy with direct local pickup or delivery',
    'market.search_placeholder': 'Search shops...',
    'market.filter_all': 'All',
    'market.filter_delivery': 'Delivery',
    'market.filter_pickup': 'Pickup Only',
    'market.filter_food': 'Food',
    'market.filter_toys': 'Toys',
    'market.filter_grooming': 'Grooming',
    'market.filter_health': 'Health',
    'market.my_orders': 'My Orders',
    'market.wishlist': 'Wishlist',
    'market.tag_delivery': 'Delivery',
    'market.tag_pickup_only': 'Pickup Only',
    'market.info_only': 'ℹ️ Info Only',
    'market.cart': 'Cart',
  },
  he: {
    'nav.emergency': 'חירום',
    'nav.community': 'קהילה',
    'nav.assistant': 'עוזר חכם',
    'nav.pets': 'בריאות וחיות',
    'nav.shops': 'חנויות',

    'action.save': 'שמור שינויים',
    'action.cancel': 'ביטול',
    'action.delete': 'מחיקה',
    'action.edit': 'עריכה',
    'action.back': 'חזרה',
    'action.close': 'סגירה',
    'action.logout': 'התנתק',
    'action.login': 'התחברות',
    'action.register': 'הרשמה',
    'action.share': 'שיתוף',
    'action.archive': 'העבר לארכיון',
    'action.restore': 'שחזר לפעיל',
    'action.call': 'חייג למרפאה',
    'action.directions': 'ניווט',
    'action.dispatch': 'שדר תיק רפואי SOS',
    'common.select_language': 'בחר שפה',

    'emergency.title': 'מרפאות חירום קרובות',
    'emergency.subtitle': 'איתור מרפאות פתוחות בזמן אמת, תור חי ושיגור נתוני מצוקה',
    'emergency.search_placeholder': 'חפש עיר או מרפאה (נוכחי: חיפה)...',
    'emergency.filter_all': 'כל המרפאות',
    'emergency.filter_open': '🟢 פתוח עכשיו',
    'emergency.filter_verified': '⭐ מאומת עם מערכת PIMS',
    'emergency.filter_247': '⭐ חירום 24/7 בלבד',
    'emergency.filter_immediate': '🚨 קליטה מיידית',
    'emergency.sos_banner_title': '🚨 חיית המחמד במצב חירום קריטי?',
    'emergency.sos_banner_desc': 'מוקד חירום וטרינרי 24/7 מיידי: 054-998-1122',
    'emergency.btn_call_emergency': 'חייג למוקד חירום עכשיו',
    'emergency.vets_nearby_prefix': 'מרפאות בסביבה',
    'emergency.sheet_drag_hint': 'גרור לשינוי גובה',
    'emergency.tag_verified_er': 'מוקד חירום מאומת 24/7',
    'emergency.tag_community_open': 'מרפאה קהילתית · פתוח עכשיו',
    'emergency.tag_closed': 'סגור כעת',
    'emergency.btn_alert_coming': '🚨 התרע למרפאה שאני בדרך',
    'emergency.btn_call': 'חייג',
    'emergency.btn_directions': 'ניווט',

    'community.title': 'קהילה ובטיחות',
    'community.subtitle': 'סטוריז, התראות אובדן ורגעים מקומיים',
    'community.share_moment': 'שתף רגע',
    'community.add_story': 'הוסף סטורי',
    'community.my_pet': 'החיה שלי+',
    'community.expire_24h': '24 שעות תפוגה',
    'community.filter_all': 'כל הפוסטים',
    'community.filter_lost': '🚨 אבדות ומציאות (30 יום)',
    'community.filter_health': '🩺 בריאות וטיפול',
    'community.filter_playdate': '🐕 מפגשים ומשחקים',
    'community.filter_cute': '✨ תמונות מתוקות',
    'community.call_owner': 'חייג לבעלים מיד',
    'community.comment_placeholder': 'הוסף תגובה או עצה...',
    'community.translate_btn': 'תרגם פוסט',
    'community.show_original': 'הצג מקור',
    'community.tag_health': '🩺 בריאות וטיפול',
    'community.tag_cute': '✨ תמונה מתוקה',
    'community.tag_playdate': '🐕 מפגש משחק',
    'community.tag_lost': '🚨 אבד דחוף',
    'community.pet_post': 'פוסט חיה',

    'profile.title': 'חיות המחמד שלי',
    'profile.managed_by': 'בניהול של',
    'profile.active_pets': '🐾 חיות פעילות',
    'profile.archived_pets': '📦 דרכונים בארכיון',
    'profile.add_pet': 'הוסף חיית מחמד',
    'profile.no_pets': 'אין עדיין חיות ברשימה זו.',
    'profile.no_archived': 'אין דרכונים בארכיון.',
    'profile.archived_badge': 'בארכיון',
    'profile.passport_heading': 'דרכון בריאות מאומת והיסטוריה קלינית',
    'profile.tab_vet_records': 'תיקים מאומתים במרפאה',
    'profile.tab_home_log': 'יומן ביתי',
    'profile.tab_spending': 'ניתוח הוצאות',
    'profile.btn_scan_record': 'סרוק מסמך / קבלה',
    'profile.btn_export_pdf': 'ייצוא דרכון ל-PDF',
    'profile.analytics_title': 'ניתוח הוצאות חודשי ומצטבר',
    'profile.total_tracked': 'סה״כ הוצאות מתועדות',
    'profile.avg_monthly': 'עלות חודשית ממוצעת',
    'profile.receipts_analyzed': 'קבלות שנותחו',

    'chat.title': 'עוזר PetSOS חכם',
    'chat.subtitle': 'ייעוץ מבוקר לבריאות חיות מחמד, תזונה ומיון ראשוני',
    'chat.input_placeholder': 'שאל כל שאלה על טיפול, תסמינים, תזונה...',
    'chat.send': 'שלח',

    'market.title': 'חנויות חיות',
    'market.subtitle': 'מזון איכותי, צעצועים וציוד עם משלוח מהיר או איסוף',
    'market.search_placeholder': 'חפש חנויות...',
    'market.filter_all': 'הכל',
    'market.filter_delivery': 'משלוח',
    'market.filter_pickup': 'איסוף בלבד',
    'market.filter_food': 'מזון',
    'market.filter_toys': 'צעצועים',
    'market.filter_grooming': 'טיפוח',
    'market.filter_health': 'בריאות',
    'market.my_orders': 'ההזמנות שלי',
    'market.wishlist': 'מועדפים',
    'market.tag_delivery': 'משלוח',
    'market.tag_pickup_only': 'איסוף בלבד',
    'market.info_only': 'ℹ️ למידע בלבד',
    'market.cart': 'עגלת קניות',
  },
  ar: {
    'nav.emergency': 'الطوارئ',
    'nav.community': 'المجتمع',
    'nav.assistant': 'المساعد',
    'nav.pets': 'الصحة والحيوانات',
    'nav.shops': 'المتاجر',

    'action.save': 'حفظ التغييرات',
    'action.cancel': 'إلغاء',
    'action.delete': 'حذف',
    'action.edit': 'تعديل',
    'action.back': 'رجوع',
    'action.close': 'إغلاق',
    'action.logout': 'تسجيل الخروج',
    'action.login': 'تسجيل الدخول',
    'action.register': 'إنشاء حساب',
    'action.share': 'مشاركة',
    'action.archive': 'أرشفة الحيوان',
    'action.restore': 'استعادة للنشط',
    'action.call': 'اتصال بالعيادة',
    'action.directions': 'الاتجاهات',
    'action.dispatch': 'إرسال ملف الطوارئ SOS',
    'common.select_language': 'اختر اللغة',

    'emergency.title': 'عيادات الطوارئ البيطرية القريبة',
    'emergency.subtitle': 'البحث عن العيادات المفتوحة وإرسال ملف الطوارئ الفوري',
    'emergency.search_placeholder': 'ابحث عن مدينة (حالياً: حيفا)...',
    'emergency.filter_all': 'جميع العيادات',
    'emergency.filter_open': '🟢 المفتوحة الآن',
    'emergency.filter_verified': '⭐ موثوقة بربط مباشر PIMS',
    'emergency.filter_247': '⭐ طوارئ 24/7 فقط',
    'emergency.filter_immediate': '🚨 استقبال فوري',
    'emergency.sos_banner_title': '🚨 حيوانك الأليف في حالة طارئة حرجة؟',
    'emergency.sos_banner_desc': 'الخط الساخن البيطري للطوارئ 24/7: 054-998-1122',
    'emergency.btn_call_emergency': 'اتصل بخط الطوارئ الآن',
    'emergency.vets_nearby_prefix': 'عيادات قريبة',
    'emergency.sheet_drag_hint': 'اسحب لضبط الارتفاع',
    'emergency.tag_verified_er': 'طوارئ بيطرية موثقة 24/7',
    'emergency.tag_community_open': 'عيادة مجتمعية · مفتوحة الآن',
    'emergency.tag_closed': 'مغلقة الآن',
    'emergency.btn_alert_coming': '🚨 تنبيه العيادة أنني قادم',
    'emergency.btn_call': 'اتصال',
    'emergency.btn_directions': 'الاتجاهات',

    'community.title': 'المجتمع والسلامة',
    'community.subtitle': 'القصص وتنبيهات الحيوانات المفقودة واللحظات المحلية',
    'community.share_moment': 'شارك لحظة',
    'community.add_story': 'إضافة قصة',
    'community.my_pet': 'حيواني الأليف+',
    'community.expire_24h': 'صلاحية 24 ساعة',
    'community.filter_all': 'كل المنشورات',
    'community.filter_lost': '🚨 المفقودات والموجودات (30 يوم)',
    'community.filter_health': '🩺 نصائح صحية ورعاية',
    'community.filter_playdate': '🐕 مواعيد اللعب',
    'community.filter_cute': '✨ لقطات لطيفة',
    'community.call_owner': 'اتصل بالمالك فوراً',
    'community.comment_placeholder': 'أضف رداً أو نصيحة...',
    'community.translate_btn': 'ترجمة المنشور',
    'community.show_original': 'عرض الأصل',
    'community.tag_health': '🩺 صحة ورعاية',
    'community.tag_cute': '✨ لقطة لطيفة',
    'community.tag_playdate': '🐕 موعد لعب',
    'community.tag_lost': '🚨 نداء طوارئ لمفقود',
    'community.pet_post': 'منشور الحيوان',

    'profile.title': 'حيواناتي الأليفة',
    'profile.managed_by': 'بإدارة',
    'profile.active_pets': '🐾 الحيوانات النشطة',
    'profile.archived_pets': '📦 الجوازات المؤرشفة',
    'profile.add_pet': 'إضافة حيوان أليف',
    'profile.no_pets': 'لا توجد حيوانات في هذه القائمة بعد.',
    'profile.no_archived': 'لا توجد جوازات مؤرشفة.',
    'profile.archived_badge': 'مؤرشف',
    'profile.passport_heading': 'جواز السفر الصحي وسجل الزيارات السريرية',
    'profile.tab_vet_records': 'السجلات المعتمدة بالعيادة',
    'profile.tab_home_log': 'سجل الملاحظات المنزلية',
    'profile.tab_spending': 'تحليل النفقات',
    'profile.btn_scan_record': 'مسح مستند / إيصال',
    'profile.btn_export_pdf': 'تصدير الجواز كـ PDF',
    'profile.analytics_title': 'تحليلات النفقات الإجمالية والشهرية',
    'profile.total_tracked': 'إجمالي النفقات المسجلة',
    'profile.avg_monthly': 'متوسط التكلفة الشهرية',
    'profile.receipts_analyzed': 'الفواتير التي تم تحليلها',

    'chat.title': 'مساعد PetSOS الذكي',
    'chat.subtitle': 'دعم بيطري آمن لصحة وتغذية الحيوانات وفرز الطوارئ',
    'chat.input_placeholder': 'اسأل أي شيء عن الرعاية أو الأعراض أو الغذاء...',
    'chat.send': 'إرسال',

    'market.title': 'متاجر الحيوانات الأليفة',
    'market.subtitle': 'طعام متميز وألعاب وصيدلية مع استلام فوري أو توصيل',
    'market.search_placeholder': 'ابحث عن المتاجر...',
    'market.filter_all': 'الكل',
    'market.filter_delivery': 'توصيل',
    'market.filter_pickup': 'استلام فقط',
    'market.filter_food': 'طعام',
    'market.filter_toys': 'ألعاب',
    'market.filter_grooming': 'عناية وتنظيف',
    'market.filter_health': 'صحة',
    'market.my_orders': 'طلباتي',
    'market.wishlist': 'المفضلة',
    'market.tag_delivery': 'توصيل',
    'market.tag_pickup_only': 'استلام فقط',
    'market.info_only': 'ℹ️ للعلم فقط',
    'market.cart': 'سلة المشتريات',
  },
  ru: {
    'nav.emergency': 'Экстренно',
    'nav.community': 'Сообщество',
    'nav.assistant': 'Ассистент',
    'nav.pets': 'Здоровье и питомцы',
    'nav.shops': 'Магазины',

    'action.save': 'Сохранить изменения',
    'action.cancel': 'Отмена',
    'action.delete': 'Удалить',
    'action.edit': 'Редактировать',
    'action.back': 'Назад',
    'action.close': 'Закрыть',
    'action.logout': 'Выйти',
    'action.login': 'Войти',
    'action.register': 'Регистрация',
    'action.share': 'Поделиться',
    'action.archive': 'Архивировать питомца',
    'action.restore': 'Восстановить',
    'action.call': 'Позвонить в клинику',
    'action.directions': 'Маршрут',
    'action.dispatch': 'Отправить досье SOS',
    'common.select_language': 'Выберите язык',

    'emergency.title': 'Экстренная ветпомощь рядом',
    'emergency.subtitle': 'Поиск открытых клиник в реальном времени и вызов помощи',
    'emergency.search_placeholder': 'Поиск города (текущий: Хайфа)...',
    'emergency.filter_all': 'Все клиники',
    'emergency.filter_open': '🟢 Открыты сейчас',
    'emergency.filter_verified': '⭐ Проверенные клиники PIMS',
    'emergency.filter_247': '⭐ Только 24/7 ER',
    'emergency.filter_immediate': '🚨 Срочный прием',
    'emergency.sos_banner_title': '🚨 ПИТОМЕЦ В КРИТИЧЕСКОМ СОСТОЯНИИ?',
    'emergency.sos_banner_desc': 'Круглосуточная горячая линия скорой ветпомощи: +972-54-998-1122',
    'emergency.btn_call_emergency': 'ПОЗВОНИТЬ В СКОРУЮ СЕЙЧАС',
    'emergency.vets_nearby_prefix': 'клиник рядом',
    'emergency.sheet_drag_hint': 'Потяните для настройки',
    'emergency.tag_verified_er': 'ПРОВЕРЕННАЯ 24/7 СКОРАЯ',
    'emergency.tag_community_open': 'ВЕТКЛИНИКА · ОТКРЫТО СЕЙЧАС',
    'emergency.tag_closed': 'ЗАКРЫТО',
    'emergency.btn_alert_coming': '🚨 Предупредить клинику: Я еду',
    'emergency.btn_call': 'Звонок',
    'emergency.btn_directions': 'Маршрут',

    'community.title': 'Сообщество и безопасность',
    'community.subtitle': 'Истории, оповещения о пропаже и моменты из жизни питомцев',
    'community.share_moment': 'Поделиться моментом',
    'community.add_story': 'Добавить историю',
    'community.my_pet': 'Мой питомец+',
    'community.expire_24h': 'Истекает через 24ч',
    'community.filter_all': 'Все моменты',
    'community.filter_lost': '🚨 Пропавшие и найденные (30д)',
    'community.filter_health': '🩺 Советы ветврачей',
    'community.filter_playdate': '🐕 Совместные прогулки',
    'community.filter_cute': '✨ Милые фото',
    'community.call_owner': 'Срочно позвонить владельцу',
    'community.comment_placeholder': 'Напишите комментарий или совет...',
    'community.translate_btn': 'Перевести пост',
    'community.show_original': 'Показать оригинал',
    'community.tag_health': '🩺 ЗДОРОВЬЕ И УХОД',
    'community.tag_cute': '✨ МИЛОЕ ФОТО',
    'community.tag_playdate': '🐕 ПРОГУЛКА',
    'community.tag_lost': '🚨 СРОЧНЫЙ ПОИСК',
    'community.pet_post': 'Пост о питомце',

    'profile.title': 'Мои питомцы',
    'profile.managed_by': 'Владелец',
    'profile.active_pets': '🐾 Активные питомцы',
    'profile.archived_pets': '📦 Архивные паспорта',
    'profile.add_pet': 'Добавить питомца',
    'profile.no_pets': 'В этом списке пока нет питомцев.',
    'profile.no_archived': 'В архиве пока пусто.',
    'profile.archived_badge': 'В АРХИВЕ',
    'profile.passport_heading': 'ПРОВЕРЕННЫЙ МЕДИЦИНСКИЙ ПАСПОРТ И ИСТОРИЯ',
    'profile.tab_vet_records': 'Подтвержденные записи (клиника)',
    'profile.tab_home_log': 'Домашний журнал',
    'profile.tab_spending': 'Аналитика расходов',
    'profile.btn_scan_record': 'Сканировать документ / чек',
    'profile.btn_export_pdf': 'Экспорт паспорта в PDF',
    'profile.analytics_title': 'Аналитика расходов за все время и по месяцам',
    'profile.total_tracked': 'Всего учтено',
    'profile.avg_monthly': 'Среднемесячные расходы',
    'profile.receipts_analyzed': 'Чеков проанализировано',

    'chat.title': 'ИИ-Ассистент PetSOS',
    'chat.subtitle': 'Безопасные советы по уходу, питанию и экстренная помощь',
    'chat.input_placeholder': 'Задайте любой вопрос о здоровье питомца...',
    'chat.send': 'Отправить',

    'market.title': 'Зоомагазины',
    'market.subtitle': 'Качественные корма, товары и лекарства с доставкой или самовывозом',
    'market.search_placeholder': 'Поиск магазинов...',
    'market.filter_all': 'Все',
    'market.filter_delivery': 'Доставка',
    'market.filter_pickup': 'Только самовывоз',
    'market.filter_food': 'Корма',
    'market.filter_toys': 'Игрушки',
    'market.filter_grooming': 'Груминг',
    'market.filter_health': 'Здоровье',
    'market.my_orders': 'Мои заказы',
    'market.wishlist': 'Избранное',
    'market.tag_delivery': 'Доставка',
    'market.tag_pickup_only': 'Только самовывоз',
    'market.info_only': 'ℹ️ Только справка',
    'market.cart': 'Корзина',
  },
  fr: {
    'nav.emergency': 'Urgences',
    'nav.community': 'Communauté',
    'nav.assistant': 'Assistant',
    'nav.pets': 'Santé & Animaux',
    'nav.shops': 'Boutiques',

    'action.save': 'Enregistrer les modifications',
    'action.cancel': 'Annuler',
    'action.delete': 'Supprimer',
    'action.edit': 'Modifier',
    'action.back': 'Retour',
    'action.close': 'Fermer',
    'action.logout': 'Se déconnecter',
    'action.login': 'Se connecter',
    'action.register': "S'inscrire",
    'action.share': 'Partager',
    'action.archive': "Archiver l'animal",
    'action.restore': 'Restaurer',
    'action.call': 'Appeler la clinique',
    'action.directions': 'Itinéraire',
    'action.dispatch': 'Envoyer le dossier SOS',
    'common.select_language': 'Choisir la langue',

    'emergency.title': 'Vétérinaires d’Urgence Proches',
    'emergency.subtitle': 'Recherche en direct de cliniques ouvertes et régulation SOS',
    'emergency.search_placeholder': 'Rechercher une ville (actuel: Haïfa)...',
    'emergency.filter_all': 'Toutes les cliniques',
    'emergency.filter_open': '🟢 Ouvert maintenant',
    'emergency.filter_verified': '⭐ Vérifié PIMS Direct',
    'emergency.filter_247': '⭐ Urgences 24/7 Uniquement',
    'emergency.filter_immediate': '🚨 Prise en charge immédiate',
    'emergency.sos_banner_title': '🚨 ANIMAL EN DÉTRESSE CRITIQUE ?',
    'emergency.sos_banner_desc': 'Ligne directe d’urgence vétérinaire 24/7 : +972-54-998-1122',
    'emergency.btn_call_emergency': 'APPELER LE NUMÉRO D’URGENCE',
    'emergency.vets_nearby_prefix': 'vétérinaires proches',
    'emergency.sheet_drag_hint': 'Glisser pour ajuster',
    'emergency.tag_verified_er': 'URGENCES VÉRIFIÉES 24/7',
    'emergency.tag_community_open': 'VÉTÉRINAIRE DE QUARTIER · OUVERT',
    'emergency.tag_closed': 'FERMÉ ACTUELLEMENT',
    'emergency.btn_alert_coming': "🚨 Alerter la clinique : J'arrive",
    'emergency.btn_call': 'Appeler',
    'emergency.btn_directions': 'Itinéraire',

    'community.title': 'Communauté & Sécurité',
    'community.subtitle': 'Stories, alertes de perte et moments de quartier',
    'community.share_moment': 'Partager un moment',
    'community.add_story': 'Ajouter une story',
    'community.my_pet': 'Mon animal+',
    'community.expire_24h': 'Expire dans 24h',
    'community.filter_all': 'Tous les moments',
    'community.filter_lost': '🚨 Perdus & Trouvés (30j)',
    'community.filter_health': '🩺 Conseils Santé & Soins',
    'community.filter_playdate': '🐕 Rencontres & Jeux',
    'community.filter_cute': '✨ Photos mignonnes',
    'community.call_owner': 'Appeler le propriétaire immédiatement',
    'community.comment_placeholder': 'Ajouter une réponse ou un conseil...',
    'community.translate_btn': 'Traduire le post',
    'community.show_original': "Voir l'original",
    'community.tag_health': '🩺 SANTÉ & SOINS',
    'community.tag_cute': '✨ INSTANT MIGNON',
    'community.tag_playdate': '🐕 JEUX',
    'community.tag_lost': '🚨 SOS ANIMAL PERDU',
    'community.pet_post': 'Publication',

    'profile.title': 'Mes Animaux',
    'profile.managed_by': 'Géré par',
    'profile.active_pets': '🐾 Animaux Actifs',
    'profile.archived_pets': '📦 Passeports Archivés',
    'profile.add_pet': 'Ajouter un animal',
    'profile.no_pets': 'Aucun animal dans cette liste pour le moment.',
    'profile.no_archived': 'Aucun passeport archivé.',
    'profile.archived_badge': 'ARCHIVÉ',
    'profile.passport_heading': 'PASSEPORT SANTÉ VÉRIFIÉ & HISTORIQUE MÉDICAL',
    'profile.tab_vet_records': 'Dossiers vérifiés clinique',
    'profile.tab_home_log': 'Journal de bord maison',
    'profile.tab_spending': 'Analyse des dépenses',
    'profile.btn_scan_record': 'Scanner un reçu / document',
    'profile.btn_export_pdf': 'Exporter le passeport en PDF',
    'profile.analytics_title': 'Analyse des dépenses globales et mensuelles',
    'profile.total_tracked': 'Total suivi',
    'profile.avg_monthly': 'Coût mensuel moyen',
    'profile.receipts_analyzed': 'Factures analysées',

    'chat.title': 'Assistant IA PetSOS',
    'chat.subtitle': 'Conseils bienveillants pour la santé, l’alimentation et le tri d’urgence',
    'chat.input_placeholder': 'Posez vos questions sur les soins, symptômes...',
    'chat.send': 'Envoyer',

    'market.title': 'Boutiques & Animaleries',
    'market.subtitle': 'Nourriture de qualité, jouets et pharmacie avec retrait ou livraison',
    'market.search_placeholder': 'Rechercher des boutiques...',
    'market.filter_all': 'Tous',
    'market.filter_delivery': 'Livraison',
    'market.filter_pickup': 'Retrait uniquement',
    'market.filter_food': 'Nourriture',
    'market.filter_toys': 'Jouets',
    'market.filter_grooming': 'Toilettage',
    'market.filter_health': 'Santé',
    'market.my_orders': 'Mes Commandes',
    'market.wishlist': 'Favoris',
    'market.tag_delivery': 'Livraison',
    'market.tag_pickup_only': 'Retrait uniquement',
    'market.info_only': 'ℹ️ Info uniquement',
    'market.cart': 'Panier',
  },
  es: {
    'nav.emergency': 'Urgencias',
    'nav.community': 'Comunidad',
    'nav.assistant': 'Asistente',
    'nav.pets': 'Salud y Mascotas',
    'nav.shops': 'Tiendas',

    'action.save': 'Guardar Cambios',
    'action.cancel': 'Cancelar',
    'action.delete': 'Eliminar',
    'action.edit': 'Editar',
    'action.back': 'Volver',
    'action.close': 'Cerrar',
    'action.logout': 'Cerrar Sesión',
    'action.login': 'Iniciar Sesión',
    'action.register': 'Registrarse',
    'action.share': 'Compartir',
    'action.archive': 'Archivar Mascota',
    'action.restore': 'Restaurar',
    'action.call': 'Llamar a Clínica',
    'action.directions': 'Cómo llegar',
    'action.dispatch': 'Enviar Dossier SOS',
    'common.select_language': 'Seleccionar idioma',

    'emergency.title': 'Veterinarias de Urgencia Cercanas',
    'emergency.subtitle': 'Buscador en tiempo real de clínicas abiertas y cola de triaje',
    'emergency.search_placeholder': 'Buscar ciudad (actual: Haifa)...',
    'emergency.filter_all': 'Todas las Clínicas',
    'emergency.filter_open': '🟢 Abiertas Ahora',
    'emergency.filter_verified': '⭐ Verificadas con PIMS',
    'emergency.filter_247': '⭐ Solo 24/7 ER',
    'emergency.filter_immediate': '🚨 Admisión Inmediata',
    'emergency.sos_banner_title': '🚨 ¿MASCOTA EN ESTADO CRÍTICO?',
    'emergency.sos_banner_desc': 'Línea directa de emergencias veterinarias 24/7: +972-54-998-1122',
    'emergency.btn_call_emergency': 'LLAMAR A URGENCIAS AHORA',
    'emergency.vets_nearby_prefix': 'veterinarias cerca',
    'emergency.sheet_drag_hint': 'Arrastra para ajustar',
    'emergency.tag_verified_er': 'URGENCIAS VERIFICADAS 24/7',
    'emergency.tag_community_open': 'VETERINARIA · ABIERTA AHORA',
    'emergency.tag_closed': 'CERRADA AHORA',
    'emergency.btn_alert_coming': '🚨 Avisar a la clínica que voy en camino',
    'emergency.btn_call': 'Llamar',
    'emergency.btn_directions': 'Ruta',

    'community.title': 'Comunidad y Seguridad',
    'community.subtitle': 'Historias, alertas de extravío y momentos locales',
    'community.share_moment': 'Compartir Momento',
    'community.add_story': 'Añadir Historia',
    'community.my_pet': 'Mi Mascota+',
    'community.expire_24h': 'Expira en 24h',
    'community.filter_all': 'Todos los Momentos',
    'community.filter_lost': '🚨 Perdidos y Encontrados (30d)',
    'community.filter_health': '🩺 Consejos Veterinarios',
    'community.filter_playdate': '🐕 Citas de Juegos',
    'community.filter_cute': '✨ Momentos Tiernos',
    'community.call_owner': 'Llamar al Dueño',
    'community.comment_placeholder': 'Escribe una respuesta o consejo...',
    'community.translate_btn': 'Traducir publicación',
    'community.show_original': 'Ver original',
    'community.tag_health': '🩺 SALUD Y CUIDADOS',
    'community.tag_cute': '✨ MOMENTO TIERNO',
    'community.tag_playdate': '🐕 JUEGOS',
    'community.tag_lost': '🚨 SOS EXTRAVÍO',
    'community.pet_post': 'Publicación',

    'profile.title': 'Mis Mascotas',
    'profile.managed_by': 'Gestionado por',
    'profile.active_pets': '🐾 Mascotas Activas',
    'profile.archived_pets': '📦 Pasaportes Archivados',
    'profile.add_pet': 'Añadir Mascota',
    'profile.no_pets': 'Aún no hay mascotas en esta lista.',
    'profile.no_archived': 'No hay pasaportes archivados.',
    'profile.archived_badge': 'ARCHIVADO',
    'profile.passport_heading': 'PASAPORTE DE SALUD VERIFICADO E HISTORIAL CLÍNICO',
    'profile.tab_vet_records': 'Registros verificados por veterinario',
    'profile.tab_home_log': 'Diario en casa',
    'profile.tab_spending': 'Análisis de gastos',
    'profile.btn_scan_record': 'Escanear recibo o historial',
    'profile.btn_export_pdf': 'Exportar pasaporte a PDF',
    'profile.analytics_title': 'Análisis de gastos acumulados y mensuales',
    'profile.total_tracked': 'Total registrado',
    'profile.avg_monthly': 'Coste medio mensual',
    'profile.receipts_analyzed': 'Recibos analizados',

    'chat.title': 'Asistente de IA PetSOS',
    'chat.subtitle': 'Bienestar, nutrición y triaje de emergencias para mascotas',
    'chat.input_placeholder': 'Pregunta sobre cuidados, síntomas, dieta...',
    'chat.send': 'Enviar',

    'market.title': 'Tiendas de Mascotas',
    'market.subtitle': 'Alimentos premium, juguetes y farmacia con recogida o entrega',
    'market.search_placeholder': 'Buscar tiendas...',
    'market.filter_all': 'Todo',
    'market.filter_delivery': 'Entrega',
    'market.filter_pickup': 'Solo Recogida',
    'market.filter_food': 'Alimento',
    'market.filter_toys': 'Juguetes',
    'market.filter_grooming': 'Peluquería',
    'market.filter_health': 'Salud',
    'market.my_orders': 'Mis Pedidos',
    'market.wishlist': 'Favoritos',
    'market.tag_delivery': 'Entrega a domicilio',
    'market.tag_pickup_only': 'Solo recogida',
    'market.info_only': 'ℹ️ Solo información',
    'market.cart': 'Carrito',
  },
  de: {
    'nav.emergency': 'Notfall',
    'nav.community': 'Gemeinschaft',
    'nav.assistant': 'Assistent',
    'nav.pets': 'Haustiere & Gesundheit',
    'nav.shops': 'Geschäfte',

    'action.save': 'Änderungen speichern',
    'action.cancel': 'Abbrechen',
    'action.delete': 'Löschen',
    'action.edit': 'Bearbeiten',
    'action.back': 'Zurück',
    'action.close': 'Schließen',
    'action.logout': 'Abmelden',
    'action.login': 'Anmelden',
    'action.register': 'Registrieren',
    'action.share': 'Teilen',
    'action.archive': 'Tier archivieren',
    'action.restore': 'Wiederherstellen',
    'action.call': 'Klinik anrufen',
    'action.directions': 'Route',
    'action.dispatch': 'SOS-Dossier senden',
    'common.select_language': 'Sprache wählen',

    'emergency.title': 'Notfall-Tierärzte in Ihrer Nähe',
    'emergency.subtitle': 'Echtzeit-Finder für geöffnete Kliniken und Notfall-Triage',
    'emergency.search_placeholder': 'Stadt suchen (aktuell: Haifa)...',
    'emergency.filter_all': 'Alle Kliniken',
    'emergency.filter_open': '🟢 Jetzt geöffnet',
    'emergency.filter_verified': '⭐ Verifiziert mit PIMS',
    'emergency.filter_247': '⭐ Nur 24/7 Notdienst',
    'emergency.filter_immediate': '🚨 Sofortige Aufnahme',
    'emergency.sos_banner_title': '🚨 TIER IN KRITISCHER NOTLAGE?',
    'emergency.sos_banner_desc': 'Tierärztliche 24/7-Notfall-Hotline: +972-54-998-1122',
    'emergency.btn_call_emergency': 'JETZT NOTFALL-HOTLINE ANRUFEN',
    'emergency.vets_nearby_prefix': 'Tierärzte in der Nähe',
    'emergency.sheet_drag_hint': 'Zum Anpassen ziehen',
    'emergency.tag_verified_er': 'VERIFIZIERTE 24/7 NOTFALLKLINIK',
    'emergency.tag_community_open': 'TIERARZTPRAXIS · JETZT GEÖFFNET',
    'emergency.tag_closed': 'DERZEIT GESCHLOSSEN',
    'emergency.btn_alert_coming': '🚨 Klinik benachrichtigen: Ich komme',
    'emergency.btn_call': 'Anrufen',
    'emergency.btn_directions': 'Route',

    'community.title': 'Gemeinschaft & Sicherheit',
    'community.subtitle': 'Stories, Vermisstenmeldungen und Momente',
    'community.share_moment': 'Moment teilen',
    'community.add_story': 'Story hinzufügen',
    'community.my_pet': 'Mein Tier+',
    'community.expire_24h': 'Läuft in 24h ab',
    'community.filter_all': 'Alle Momente',
    'community.filter_lost': '🚨 Vermisst & Gefunden (30T)',
    'community.filter_health': '🩺 Tierarzt-Tipps',
    'community.filter_playdate': '🐕 Spieldates',
    'community.filter_cute': '✨ Süße Schnappschüsse',
    'community.call_owner': 'Halter sofort anrufen',
    'community.comment_placeholder': 'Antworten oder Tipp geben...',
    'community.translate_btn': 'Beitrag übersetzen',
    'community.show_original': 'Original anzeigen',
    'community.tag_health': '🩺 GESUNDHEIT & PFLEGE',
    'community.tag_cute': '✨ SÜSSER MOMENT',
    'community.tag_playdate': '🐕 SPIELEN',
    'community.tag_lost': '🚨 VERMISSTEN-SOS',
    'community.pet_post': 'Beitrag',

    'profile.title': 'Meine Haustiere',
    'profile.managed_by': 'Verwaltet von',
    'profile.active_pets': '🐾 Aktive Tiere',
    'profile.archived_pets': '📦 Archivierte Pässe',
    'profile.add_pet': 'Neues Tier hinzufügen',
    'profile.no_pets': 'Noch keine Tiere in dieser Liste.',
    'profile.no_archived': 'Keine archivierten Pässe.',
    'profile.archived_badge': 'ARCHIVIERT',
    'profile.passport_heading': 'VERIFIZIERTER GESUNDHEITSPASS & KLINISCHE HISTORIE',
    'profile.tab_vet_records': 'Tierärztlich geprüfte Akten',
    'profile.tab_home_log': 'Heimtagebuch',
    'profile.tab_spending': 'Ausgabenanalyse',
    'profile.btn_scan_record': 'Beleg / Akte scannen',
    'profile.btn_export_pdf': 'Gesundheitspass als PDF exportieren',
    'profile.analytics_title': 'Gesamt- & Monatsausgaben-Analyse',
    'profile.total_tracked': 'Gesamt erfasst',
    'profile.avg_monthly': 'Durchschnittliche Monatskosten',
    'profile.receipts_analyzed': 'Analysierte Belege',

    'chat.title': 'PetSOS KI-Assistent',
    'chat.subtitle': 'Sichere Tiergesundheit, Ernährung und Notfallberatung',
    'chat.input_placeholder': 'Frage zu Pflege, Symptomen, Ernährung...',
    'chat.send': 'Senden',

    'market.title': 'Tierbedarf & Futter',
    'market.subtitle': 'Premium-Futter, Spielzeug und Apotheke mit Lieferung oder Abholung',
    'market.search_placeholder': 'Geschäfte durchsuchen...',
    'market.filter_all': 'Alle',
    'market.filter_delivery': 'Lieferung',
    'market.filter_pickup': 'Nur Abholung',
    'market.filter_food': 'Futter',
    'market.filter_toys': 'Spielzeug',
    'market.filter_grooming': 'Pflege',
    'market.filter_health': 'Gesundheit',
    'market.my_orders': 'Meine Bestellungen',
    'market.wishlist': 'Wunschliste',
    'market.tag_delivery': 'Lieferung',
    'market.tag_pickup_only': 'Nur Abholung',
    'market.info_only': 'ℹ️ Nur Info',
    'market.cart': 'Warenkorb',
  },
  it: {
    'nav.emergency': 'Emergenza',
    'nav.community': 'Comunità',
    'nav.assistant': 'Assistente',
    'nav.pets': 'Salute & Animali',
    'nav.shops': 'Negozi',

    'action.save': 'Salva modifiche',
    'action.cancel': 'Annulla',
    'action.delete': 'Elimina',
    'action.edit': 'Modifica',
    'action.back': 'Indietro',
    'action.close': 'Chiudi',
    'action.logout': 'Disconnetti',
    'action.login': 'Accedi',
    'action.register': 'Registrati',
    'action.share': 'Condividi',
    'action.archive': 'Archivia animale',
    'action.restore': 'Ripristina',
    'action.call': 'Chiama clinica',
    'action.directions': 'Indicazioni',
    'action.dispatch': 'Invia dossier SOS',
    'common.select_language': 'Seleziona lingua',

    'emergency.title': 'Veterinari di Emergenza Vicini',
    'emergency.subtitle': 'Trova cliniche aperte in tempo reale e invio SOS',
    'emergency.search_placeholder': 'Cerca città (attuale: Haifa)...',
    'emergency.filter_all': 'Tutte le cliniche',
    'emergency.filter_open': '🟢 Aperto ora',
    'emergency.filter_verified': '⭐ Verificato PIMS Direct',
    'emergency.filter_247': '⭐ Solo 24/7 ER',
    'emergency.filter_immediate': '🚨 Accoglienza Immediata',
    'emergency.sos_banner_title': '🚨 ANIMALE IN GRAVE PERICOLO?',
    'emergency.sos_banner_desc': 'Pronto soccorso veterinario 24/7: +972-54-998-1122',
    'emergency.btn_call_emergency': 'CHIAMA IL PRONTO SOCCORSO ORA',
    'emergency.vets_nearby_prefix': 'veterinari vicini',
    'emergency.sheet_drag_hint': 'Trascina per regolare',
    'emergency.tag_verified_er': 'PRONTO SOCCORSO VERIFICATO 24/7',
    'emergency.tag_community_open': 'CLINICA DI QUARTIERE · APERTA ORA',
    'emergency.tag_closed': 'ATTUALMENTE CHIUSO',
    'emergency.btn_alert_coming': '🚨 Avvisa la clinica: Sto arrivando',
    'emergency.btn_call': 'Chiama',
    'emergency.btn_directions': 'Indicazioni',

    'community.title': 'Comunità & Sicurezza',
    'community.subtitle': 'Storie, avvisi di smarrimento e momenti locali',
    'community.share_moment': 'Condividi momento',
    'community.add_story': 'Aggiungi storia',
    'community.my_pet': 'Il mio animale+',
    'community.expire_24h': 'Scade in 24h',
    'community.filter_all': 'Tutti i momenti',
    'community.filter_lost': '🚨 Smarriti & Trovati (30g)',
    'community.filter_health': '🩺 Consigli di salute',
    'community.filter_playdate': '🐕 Incontri di gioco',
    'community.filter_cute': '✨ Momenti dolci',
    'community.call_owner': 'Chiama proprietario subito',
    'community.comment_placeholder': 'Aggiungi un commento...',
    'community.translate_btn': 'Traduci post',
    'community.show_original': 'Mostra originale',
    'community.tag_health': '🩺 SALUTE & CURA',
    'community.tag_cute': '✨ MOMENTO DOLCE',
    'community.tag_playdate': '🐕 GIOCO',
    'community.tag_lost': '🚨 SOS SMARRIMENTO',
    'community.pet_post': 'Post',

    'profile.title': 'I Miei Animali',
    'profile.managed_by': 'Gestito da',
    'profile.active_pets': '🐾 Animali Attivi',
    'profile.archived_pets': '📦 Passaporti Archiviati',
    'profile.add_pet': 'Aggiungi animale',
    'profile.no_pets': 'Nessun animale in questa lista.',
    'profile.no_archived': 'Nessun passaporto archiviato.',
    'profile.archived_badge': 'ARCHIVIATO',
    'profile.passport_heading': 'PASSAPORTO SANITARIO VERIFICATO E STORICO CLINICO',
    'profile.tab_vet_records': 'Cartelle verificate da clinica',
    'profile.tab_home_log': 'Diario di casa',
    'profile.tab_spending': 'Analisi delle spese',
    'profile.btn_scan_record': 'Scansiona referto / scontrino',
    'profile.btn_export_pdf': 'Esporta passaporto in PDF',
    'profile.analytics_title': 'Analisi delle spese complessive e mensili',
    'profile.total_tracked': 'Totale tracciato',
    'profile.avg_monthly': 'Costo medio mensile',
    'profile.receipts_analyzed': 'Ricevute analizzate',

    'chat.title': 'Assistente IA PetSOS',
    'chat.subtitle': 'Consigli sicuri su benessere, nutrizione e supporto di emergenza',
    'chat.input_placeholder': 'Fai una domanda su salute, sintomi, dieta...',
    'chat.send': 'Invia',

    'market.title': 'Negozi per Animali',
    'market.subtitle': 'Cibo premium, accessori e farmacia con consegna rapida o ritiro',
    'market.search_placeholder': 'Cerca negozi...',
    'market.filter_all': 'Tutti',
    'market.filter_delivery': 'Consegna',
    'market.filter_pickup': 'Solo Ritiro',
    'market.filter_food': 'Cibo',
    'market.filter_toys': 'Giochi',
    'market.filter_grooming': 'Toelettatura',
    'market.filter_health': 'Salute',
    'market.my_orders': 'I Miei Ordini',
    'market.wishlist': 'Preferiti',
    'market.tag_delivery': 'Consegna',
    'market.tag_pickup_only': 'Solo ritiro',
    'market.info_only': 'ℹ️ Solo info',
    'market.cart': 'Carrello',
  },
  pt: {
    'nav.emergency': 'Emergência',
    'nav.community': 'Comunidade',
    'nav.assistant': 'Assistente',
    'nav.pets': 'Saúde & Pets',
    'nav.shops': 'Lojas',

    'action.save': 'Salvar alterações',
    'action.cancel': 'Cancelar',
    'action.delete': 'Excluir',
    'action.edit': 'Editar',
    'action.back': 'Voltar',
    'action.close': 'Fechar',
    'action.logout': 'Sair',
    'action.login': 'Entrar',
    'action.register': 'Cadastrar',
    'action.share': 'Compartilhar',
    'action.archive': 'Arquivar pet',
    'action.restore': 'Restaurar',
    'action.call': 'Ligar para clínica',
    'action.directions': 'Como chegar',
    'action.dispatch': 'Enviar dossiê SOS',
    'common.select_language': 'Selecionar idioma',

    'emergency.title': 'Veterinários de Emergência Próximos',
    'emergency.subtitle': 'Localizador em tempo real de clínicas abertas e envio de SOS',
    'emergency.search_placeholder': 'Buscar cidade (atual: Haifa)...',
    'emergency.filter_all': 'Todas as clínicas',
    'emergency.filter_open': '🟢 Aberto agora',
    'emergency.filter_verified': '⭐ Verificado PIMS Direct',
    'emergency.filter_247': '⭐ Apenas 24/7 ER',
    'emergency.filter_immediate': '🚨 Atendimento Imediato',
    'emergency.sos_banner_title': '🚨 PET EM ESTADO CRÍTICO?',
    'emergency.sos_banner_desc': 'Plantão de emergência veterinária 24/7: +972-54-998-1122',
    'emergency.btn_call_emergency': 'LIGAR PARA O PLANTÃO AGORA',
    'emergency.vets_nearby_prefix': 'veterinários próximos',
    'emergency.sheet_drag_hint': 'Arraste para ajustar',
    'emergency.tag_verified_er': 'EMERGÊNCIA VERIFICADA 24/7',
    'emergency.tag_community_open': 'CLÍNICA DO BAIRRO · ABERTA AGORA',
    'emergency.tag_closed': 'FECHADO NO MOMENTO',
    'emergency.btn_alert_coming': '🚨 Avisar a clínica: Estou a caminho',
    'emergency.btn_call': 'Ligar',
    'emergency.btn_directions': 'Rotas',

    'community.title': 'Comunidade & Segurança',
    'community.subtitle': 'Stories, alertas de pets perdidos e momentos locais',
    'community.share_moment': 'Compartilhar momento',
    'community.add_story': 'Adicionar story',
    'community.my_pet': 'Meu pet+',
    'community.expire_24h': 'Expira em 24h',
    'community.filter_all': 'Todos os momentos',
    'community.filter_lost': '🚨 Perdidos & Encontrados (30d)',
    'community.filter_health': '🩺 Dicas Veterinárias',
    'community.filter_playdate': '🐕 Encontros para brincar',
    'community.filter_cute': '✨ Fotos fofas',
    'community.call_owner': 'Ligar para o dono imediatamente',
    'community.comment_placeholder': 'Adicione um comentário ou dica...',
    'community.translate_btn': 'Traduzir publicação',
    'community.show_original': 'Ver original',
    'community.tag_health': '🩺 SAÚDE & CUIDADOS',
    'community.tag_cute': '✨ MOMENTO FOFO',
    'community.tag_playdate': '🐕 BRINCADEIRAS',
    'community.tag_lost': '🚨 SOS ANIMAL PERDIDO',
    'community.pet_post': 'Publicação',

    'profile.title': 'Meus Pets',
    'profile.managed_by': 'Gerenciado por',
    'profile.active_pets': '🐾 Pets Ativos',
    'profile.archived_pets': '📦 Passaportes Arquivados',
    'profile.add_pet': 'Adicionar pet',
    'profile.no_pets': 'Nenhum pet nesta lista ainda.',
    'profile.no_archived': 'Nenhum passaporte arquivado.',
    'profile.archived_badge': 'ARQUIVADO',
    'profile.passport_heading': 'PASSAPORTE DE SAÚDE VERIFICADO E HISTÓRICO CLÍNICO',
    'profile.tab_vet_records': 'Prontuários verificados por clínica',
    'profile.tab_home_log': 'Diário de casa',
    'profile.tab_spending': 'Análise de gastos',
    'profile.btn_scan_record': 'Escanear comprovante / prontuário',
    'profile.btn_export_pdf': 'Exportar passaporte em PDF',
    'profile.analytics_title': 'Análise de gastos acumulados e mensais',
    'profile.total_tracked': 'Total registrado',
    'profile.avg_monthly': 'Custo médio mensal',
    'profile.receipts_analyzed': 'Recibos analisados',

    'chat.title': 'Assistente de IA PetSOS',
    'chat.subtitle': 'Dicas confiáveis de saúde, nutrição e triagem de emergência',
    'chat.input_placeholder': 'Pergunte sobre cuidados, sintomas, alimentação...',
    'chat.send': 'Enviar',

    'market.title': 'Pet Shops & Produtos',
    'market.subtitle': 'Rações premium, brinquedos e farmácia com entrega ou retirada',
    'market.search_placeholder': 'Buscar lojas...',
    'market.filter_all': 'Todos',
    'market.filter_delivery': 'Entrega',
    'market.filter_pickup': 'Apenas Retirada',
    'market.filter_food': 'Alimentos',
    'market.filter_toys': 'Brinquedos',
    'market.filter_grooming': 'Banho e Tosa',
    'market.filter_health': 'Saúde',
    'market.my_orders': 'Meus Pedidos',
    'market.wishlist': 'Favoritos',
    'market.tag_delivery': 'Entrega',
    'market.tag_pickup_only': 'Apenas retirada',
    'market.info_only': 'ℹ️ Apenas informativo',
    'market.cart': 'Carrinho',
  },
};

interface LanguageContextType {
  currentLang: LanguageCode;
  lang: LanguageCode;
  setLang: (lang: LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
  isRTL: boolean;
  languages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLang, setCurrentLangState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('petsos_lang') as LanguageCode;
    return saved && TRANSLATIONS[saved] ? saved : 'en';
  });

  const selectedOption = SUPPORTED_LANGUAGES.find((l) => l.code === currentLang) || SUPPORTED_LANGUAGES[0];
  const isRTL = selectedOption.dir === 'rtl';

  useEffect(() => {
    localStorage.setItem('petsos_lang', currentLang);
    document.documentElement.lang = currentLang;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
  }, [currentLang, isRTL]);

  const setLang = (lang: LanguageCode) => {
    if (TRANSLATIONS[lang]) {
      localStorage.setItem('petsos_lang_manual', 'true');
      localStorage.setItem('petsos_lang', lang);
      setCurrentLangState(lang);
    }
  };

  const t = (key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[currentLang];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Fallback to English
    if (TRANSLATIONS.en[key]) {
      return TRANSLATIONS.en[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLang,
        lang: currentLang,
        setLang,
        t,
        isRTL,
        languages: SUPPORTED_LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
