import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Appointment, AppointmentDocument } from '../schemas/appointment.schema';
import { Reminder, ReminderDocument } from '../schemas/reminder.schema';
import { PetProfile, PetProfileDocument } from '../schemas/pet-profile.schema';

@Injectable()
export class ScheduleService {
  constructor(
    @InjectModel(Appointment.name)
    private appointmentModel: Model<AppointmentDocument>,
    @InjectModel(Reminder.name)
    private reminderModel: Model<ReminderDocument>,
    @InjectModel(PetProfile.name)
    private petModel: Model<PetProfileDocument>,
  ) {}

  async bookAppointment(dto: any): Promise<Appointment> {
    let coParentIds: string[] = [];
    let petColor = dto.petColor || '#f97316';
    let petPassportId = dto.petPassportId;

    if (dto.petId) {
      try {
        const pet = await this.petModel.findById(dto.petId);
        if (pet) {
          coParentIds = (pet.coParents || []).map((cp: any) => cp.userId);
          petPassportId = pet.petId || petPassportId;
          if (pet.species === 'cat') petColor = '#0ea5e9';
          else if (pet.species === 'bird') petColor = '#10b981';
          else if (pet.species === 'small_mammal') petColor = '#a855f7';
        }
      } catch {}
    }

    const appt = new this.appointmentModel({
      ...dto,
      petPassportId,
      petColor,
      coParentIds,
      status: 'confirmed',
    });
    const saved = await appt.save();

    // Auto-create calendar reminder for this visit
    const reminderType =
      dto.providerType === 'groomer'
        ? 'grooming'
        : dto.providerType === 'dog_walker'
          ? 'walking'
          : dto.providerType === 'pet_sitter'
            ? 'sitting'
            : 'vet_visit';

    const reminder = new this.reminderModel({
      petId: dto.petId || 'general',
      petName: dto.petName || 'Pet',
      petColor,
      userId: dto.ownerId || 'guest',
      coParentIds,
      title: `${dto.serviceName} at ${dto.providerName}`,
      type: reminderType,
      dueDate: dto.appointmentDate,
      dueTime: dto.timeSlot,
      recurrence: 'once',
      notes: dto.notes,
      isCompleted: false,
      isAutoGenerated: true,
    });
    await reminder.save();

    return saved;
  }

  async getAppointmentsForPet(petId: string): Promise<Appointment[]> {
    return this.appointmentModel
      .find({ petId, status: { $ne: 'cancelled' } })
      .sort({ appointmentDate: 1, timeSlot: 1 })
      .exec();
  }

  async getAppointmentsForUser(userId: string): Promise<Appointment[]> {
    return this.appointmentModel
      .find({
        $or: [{ ownerId: userId }, { coParentIds: userId }],
        status: { $ne: 'cancelled' },
      })
      .sort({ appointmentDate: 1, timeSlot: 1 })
      .exec();
  }

  async cancelAppointment(id: string): Promise<Appointment> {
    const appt = await this.appointmentModel.findByIdAndUpdate(
      id,
      { status: 'cancelled' },
      { new: true },
    );
    if (!appt) throw new NotFoundException('Appointment not found');
    return appt;
  }

  async getRemindersForPet(petId: string): Promise<Reminder[]> {
    return this.reminderModel
      .find({ petId })
      .sort({ dueDate: 1, dueTime: 1 })
      .exec();
  }

  async getRemindersForUser(userId: string): Promise<Reminder[]> {
    return this.reminderModel
      .find({ $or: [{ userId }, { coParentIds: userId }] })
      .sort({ dueDate: 1, dueTime: 1 })
      .exec();
  }

  async createReminder(dto: any): Promise<Reminder> {
    let coParentIds: string[] = [];
    if (dto.petId) {
      try {
        const pet = await this.petModel.findById(dto.petId);
        if (pet) {
          coParentIds = (pet.coParents || []).map((cp: any) => cp.userId);
        }
      } catch {}
    }
    const rem = new this.reminderModel({ ...dto, coParentIds });
    return rem.save();
  }

  async toggleReminder(id: string): Promise<Reminder> {
    const rem = await this.reminderModel.findById(id);
    if (!rem) throw new NotFoundException('Reminder not found');
    rem.isCompleted = !rem.isCompleted;
    rem.completedAt = rem.isCompleted ? new Date() : undefined;
    return rem.save();
  }

  async deleteReminder(id: string): Promise<{ success: boolean }> {
    await this.reminderModel.findByIdAndDelete(id);
    return { success: true };
  }
}
